// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE1Ik53vxOkx5dqe3ASjcmzuah6vYsmmU',
    appId: '1:273633405697:web:0bc1b60cb683edd77e4900',
    messagingSenderId: '273633405697',
    projectId: 'pet-care-bb7c5',
    authDomain: 'pet-care-bb7c5.firebaseapp.com',
    storageBucket: 'pet-care-bb7c5.firebasestorage.app',
    measurementId: 'G-H3GNNCZ4Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2IqtVtOf7CLZG1Zoss2hV8JPz0fQ4c5Y',
    appId: '1:273633405697:android:694efd53c27926097e4900',
    messagingSenderId: '273633405697',
    projectId: 'pet-care-bb7c5',
    storageBucket: 'pet-care-bb7c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgAVxJv1sjl_A0915vmBvlJgfWF8vskus',
    appId: '1:273633405697:ios:3d8890b79601169d7e4900',
    messagingSenderId: '273633405697',
    projectId: 'pet-care-bb7c5',
    storageBucket: 'pet-care-bb7c5.firebasestorage.app',
    iosBundleId: 'com.example.petClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgAVxJv1sjl_A0915vmBvlJgfWF8vskus',
    appId: '1:273633405697:ios:3d8890b79601169d7e4900',
    messagingSenderId: '273633405697',
    projectId: 'pet-care-bb7c5',
    storageBucket: 'pet-care-bb7c5.firebasestorage.app',
    iosBundleId: 'com.example.petClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE1Ik53vxOkx5dqe3ASjcmzuah6vYsmmU',
    appId: '1:273633405697:web:8411179e13b05a7d7e4900',
    messagingSenderId: '273633405697',
    projectId: 'pet-care-bb7c5',
    authDomain: 'pet-care-bb7c5.firebaseapp.com',
    storageBucket: 'pet-care-bb7c5.firebasestorage.app',
    measurementId: 'G-DWW2X4GMMK',
  );
}
